(() => {
  if(document.getElementById('pokerino-front-style'))return;
  const s=document.createElement('style');s.id='pokerino-front-style';s.textContent=`
    :root{--pokerino-green:#061713;--pokerino-green-2:#0a241d;--pokerino-gold:#ffc83d;--pokerino-orange:#f39a32;--pokerino-blue:#3ca9ff;--pokerino-purple:#9b62ff}
    body{background:radial-gradient(circle at 50% -10%,#143b2d 0,#07130f 36%,#030806 100%)!important}
    .app{background:linear-gradient(180deg,#071711 0%,#03100c 100%)!important}
    .brand{background:rgba(3,13,10,.94)!important;border-bottom:1px solid rgba(255,200,61,.28)!important}
    .pokerino-real .pokerino-photo{position:absolute;inset:0;background-image:url('./assets/pokerino/pokerino-hero.jpg');background-size:cover;background-position:center;background-repeat:no-repeat;border-radius:28px}.pokerino-real{overflow:hidden;border-radius:28px}.pokerino-mascot{position:absolute;right:4px;bottom:-4px;width:146px;height:166px;pointer-events:none;filter:drop-shadow(0 12px 18px rgba(0,0,0,.42));transform:scale(1.08);transform-origin:right bottom}
    
    .academy-home-hero,.academy-stage-intro,.academy-profile-head{position:relative!important;min-height:230px!important;background:radial-gradient(circle at 78% 30%,rgba(242,151,48,.38),transparent 26%),linear-gradient(125deg,#071b14,#0d3b2c 62%,#3e260d)!important;filter:none!important;border:1px solid rgba(255,200,61,.32)!important;border-radius:0 0 28px 28px!important;overflow:hidden!important}
    .academy-home-hero .academy-hero-content,.academy-stage-hero-grid,.academy-profile-hero-grid{position:relative;z-index:2;max-width:calc(100% - 150px)!important}
    .academy-title{font-size:20px!important;line-height:1.05!important;color:#fff!important}.academy-kicker,.academy-group-title,.academy-section-heading h2{color:var(--pokerino-gold)!important}
    .academy-stage-grid{grid-template-columns:1fr!important;gap:11px!important}.academy-stage-grid .academy-stage-card:last-child:nth-child(odd){grid-column:1/-1}
    .academy-stage-card{position:relative;min-height:104px!important;border-radius:22px!important;padding:16px 62px 16px 16px!important;overflow:hidden!important;background:linear-gradient(145deg,#12392c,#071c16)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.05)!important}
    .academy-stage-card:after{content:'›';position:absolute;right:15px;top:50%;transform:translateY(-50%);width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#ffc83d;color:#171006;font-size:27px}.academy-stage-card:nth-child(1){background:linear-gradient(145deg,#4d2912,#18110a)!important}.academy-stage-card:nth-child(2){background:linear-gradient(145deg,#112e52,#081522)!important}.academy-stage-card:nth-child(3){background:linear-gradient(145deg,#11412d,#071b13)!important}.academy-stage-card:nth-child(1):before{content:'♠';position:absolute;right:62px;bottom:-16px;font-size:82px;color:rgba(255,200,61,.08)}.academy-stage-card:nth-child(2):before{content:'♦';position:absolute;right:62px;bottom:-16px;font-size:82px;color:rgba(60,169,255,.10)}.academy-stage-card:nth-child(3):before{content:'★';position:absolute;right:62px;bottom:-10px;font-size:70px;color:rgba(255,255,255,.08)}
    .academy-stage-name{font-size:16px!important}.academy-home-section .academy-section-heading h2{font-size:15px!important}.academy-continue h3{font-size:18px!important}.academy-continue{position:relative;overflow:hidden}.academy-continue:after{content:'›';position:absolute;right:14px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--pokerino-gold);color:#151006;font-size:28px}.academy-continue-top{padding-right:46px}.academy-evolution-summary{border-radius:16px!important;overflow:hidden}.academy-weekly{border-radius:16px!important;background:linear-gradient(145deg,#102d23,#061610)!important}.academy-stage-step{color:var(--pokerino-gold)!important}.academy-stage-progress>i{background:linear-gradient(90deg,var(--pokerino-orange),var(--pokerino-gold))!important}
    .academy-continue,.academy-row,.academy-practice-card,.academy-plan,.academy-addon,.academy-cross-sell,.academy-app-card,.academy-coach-box,.block,.detail-card,.m2-card,.mg-card{border-color:rgba(255,200,61,.42)!important;border-radius:16px!important;background:linear-gradient(145deg,rgba(14,42,33,.96),rgba(5,21,16,.98))!important;box-shadow:0 7px 20px rgba(0,0,0,.16)!important}
    .academy-row-num{background:#173d30!important;color:var(--pokerino-gold)!important}.academy-row-arrow{color:var(--pokerino-gold)!important}
    .academy-primary{background:linear-gradient(135deg,#ffd455,#f4ad25)!important;color:#151006!important;border-color:#ffd455!important}.academy-secondary.active{background:var(--pokerino-gold)!important;color:#161108!important}
    .academy-bottom-nav{background:rgba(2,13,10,.97)!important;border-top-color:rgba(255,200,61,.32)!important}.academy-nav-item{border-radius:14px!important}.academy-nav-item.active{color:var(--pokerino-gold)!important;background:linear-gradient(180deg,rgba(255,200,61,.14),rgba(255,200,61,.02))!important}.academy-nav-item.active svg{filter:drop-shadow(0 0 6px rgba(255,200,61,.5))}
    .pokerino-guide{display:grid;grid-template-columns:74px minmax(0,1fr);gap:12px;align-items:center;padding:12px;border:1px solid rgba(255,200,61,.4);border-radius:18px;background:linear-gradient(135deg,#102d23,#071713);margin-bottom:14px}.pokerino-mini{position:relative;width:68px;height:72px;overflow:hidden;border-radius:50%;border:2px solid var(--pokerino-gold)}.pokerino-mini .pokerino-mascot{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;transform:none!important;filter:none!important;border-radius:50%!important}.pokerino-mini .pokerino-photo{background-size:cover!important;background-position:center!important;border-radius:50%!important}.pokerino-guide strong{display:block;color:var(--pokerino-gold);font-size:14px}.pokerino-guide span{display:block;margin-top:4px;color:#d5d2c8;font-size:12px;line-height:1.35}
    @media(max-width:350px){.pokerino-mascot{right:5px;transform:scale(.86);transform-origin:right bottom}.academy-home-hero .academy-hero-content,.academy-stage-hero-grid,.academy-profile-hero-grid{max-width:calc(100% - 92px)!important}.academy-title{font-size:18px!important}}
  `;document.head.appendChild(s);
  const mascot=()=>'<div class="pokerino-mascot pokerino-real" aria-hidden="true"><div class="pokerino-photo"></div></div>';
  const guide=(message)=>'<div class="pokerino-guide"><div class="pokerino-mini">'+mascot()+'</div><div><strong>POKERINO</strong><span>'+message+'</span></div></div>';
  const decorate=()=>{
    document.querySelectorAll('.academy-home-hero,.academy-stage-intro,.academy-profile-head').forEach(el=>{if(!el.querySelector(':scope > .pokerino-mascot'))el.insertAdjacentHTML('beforeend',mascot())});
    const home=document.querySelector('.academy-home');if(home&&!home.querySelector('.pokerino-guide')){const first=home.querySelector('.academy-home-section');first?.insertAdjacentHTML('beforebegin',guide('Eu vou acompanhar sua evolução. Escolha uma etapa e vamos para a mesa!'))}
    const stage=document.querySelector('.academy-stage-screen');if(stage&&!stage.querySelector('.pokerino-guide')){stage.querySelector('.academy-group')?.insertAdjacentHTML('beforebegin',guide('Aprenda no seu ritmo. Cada aula concluída deixa seu jogo mais forte.'))}
  };
  new MutationObserver(()=>requestAnimationFrame(decorate)).observe(document.getElementById('root'),{childList:true,subtree:true});
  decorate();
})();