(() => {
  const esc=v=>window.AcademyDOM?.esc(v)||String(v??'');
  const modalityWorlds=[
    {id:'holdem',name:"TEXAS HOLD'EM",icon:'♠',copy:'Duas cartas fechadas, cinco comunitárias e decisões por streets.'},
    {id:'omaha',name:'OMAHA',icon:'♦',copy:'Quatro cartas na mão e exatamente duas delas formando o jogo.'},
    {id:'omaha5',name:'OMAHA 5',icon:'♥',copy:'Mais combinações, mais draws e leitura cuidadosa de nuts.'},
    {id:'stud',name:'STUD',icon:'♣',copy:'Sem flop: informação aparece carta por carta.'},
    {id:'mixed',name:'MIXED GAMES',icon:'◎',copy:'Regras e raciocínios mudam durante a própria sessão.'}
  ];
  const stories={
    fundamentos:{eyebrow:'CAPÍTULO 1 · PRIMEIROS PASSOS',title:'A MESA GANHA VIDA',text:'Pokerino chega à mesa pela primeira vez. Antes de pensar em vencer, ele precisa entender posições, cartas, apostas e o ritmo de cada rodada.',beats:['Observe quem fala primeiro e quem decide por último.','Toque nos pontos da mesa para descobrir o papel de cada posição.','Complete a pequena missão para liberar a próxima aula.']},
    modalidades:{eyebrow:'CAPÍTULO 2 · NOVOS MUNDOS',title:'CADA JOGO, UMA NOVA REGRA',text:'Pokerino já domina a base. Agora ele entra em novas mesas e descobre como Hold’em, Omaha, Stud e outras modalidades mudam a forma de pensar.',beats:['Escolha uma modalidade para explorar.','Compare as regras antes de jogar.','Resolva a situação final para avançar.']},
    pratica:{eyebrow:'CAPÍTULO 3 · HORA DO JOGO',title:'DECISÕES NA MESA',text:'Chegou a hora de transformar conhecimento em decisão. Pokerino vai jogar ao seu lado enquanto você resolve situações reais e recebe feedback imediato.',beats:['Leia a situação.','Escolha sua decisão.','Veja a explicação e tente novamente quando precisar.']}
  };
  let utterance=null;
  const stop=()=>{try{speechSynthesis.cancel()}catch(_){};utterance=null};
  const speak=text=>{stop();if(!('speechSynthesis'in window))return;utterance=new SpeechSynthesisUtterance(text);utterance.lang='pt-BR';utterance.rate=.92;speechSynthesis.speak(utterance)};
  const modalityMap=()=>'<div class="pokerino-worlds"><div class="pokerino-worlds-title">ESCOLHA O MUNDO QUE QUER EXPLORAR</div>'+modalityWorlds.map((m,i)=>'<button type="button" data-poker-world="'+m.id+'"><b>'+m.icon+'</b><span><strong>'+m.name+'</strong><small>'+m.copy+'</small></span><i>'+(i+1)+'</i></button>').join('')+'</div>';
  const open=stage=>{
    const story=stories[stage]||stories.fundamentos;
    document.querySelector('[data-pokerino-story]')?.remove();
    const modal=document.createElement('div');modal.className='pokerino-story-overlay';modal.dataset.pokerinoStory=stage;
    modal.innerHTML=`<section class="pokerino-story-card"><button class="pokerino-story-close" type="button" data-story-close aria-label="Fechar">×</button><div class="pokerino-story-scene"><div class="pokerino-story-glow"></div><div class="pokerino-story-avatar pokerino-story-real"></div><span>POKERINO</span></div><div class="pokerino-story-copy"><div class="pokerino-story-eyebrow">${esc(story.eyebrow)}</div><h2>${esc(story.title)}</h2><p>${esc(story.text)}</p><div class="pokerino-story-beats">${story.beats.map((b,i)=>`<button type="button" data-story-beat="${i}"><b>${i+1}</b><span>${esc(b)}</span></button>`).join('')}</div><div class="pokerino-story-actions"><button type="button" class="pokerino-audio" data-story-audio>▶ OUVIR POKERINO</button><button type="button" class="pokerino-go" data-story-go>COMEÇAR CAPÍTULO ›</button></div></div></section>`;
    document.body.appendChild(modal);requestAnimationFrame(()=>modal.classList.add('show'));
  };
  const style=document.createElement('style');style.textContent=`
    .pokerino-story-overlay{position:fixed;inset:0;z-index:9999;display:grid;align-items:end;background:rgba(0,5,4,.72);backdrop-filter:blur(8px);opacity:0;transition:.2s}.pokerino-story-overlay.show{opacity:1}.pokerino-story-card{position:relative;max-width:560px;width:100%;max-height:92dvh;margin:auto;background:linear-gradient(180deg,#0d3025,#04130f 55%,#020b08);border:1px solid rgba(255,200,61,.52);border-radius:28px 28px 0 0;overflow:auto;box-shadow:0 -20px 60px rgba(0,0,0,.45)}.pokerino-story-close{position:absolute;right:14px;top:14px;z-index:3;width:38px;height:38px;border-radius:50%;border:1px solid rgba(255,255,255,.2);background:rgba(0,0,0,.38);color:white;font-size:24px}.pokerino-story-scene{height:300px;position:relative;display:grid;place-items:center;background:radial-gradient(circle at 50% 35%,rgba(255,184,53,.48),transparent 25%),linear-gradient(180deg,#174d39,#071a14);overflow:hidden}.pokerino-story-scene:before{content:'♠  ♥  ♣  ♦';position:absolute;font-size:74px;letter-spacing:18px;color:rgba(255,255,255,.035);transform:rotate(-8deg)}.pokerino-story-glow{position:absolute;width:180px;height:180px;border-radius:50%;background:rgba(255,184,53,.16);filter:blur(18px)}.pokerino-story-real{background-image:url('./assets/pokerino/pokerino-hero.png')!important;background-size:cover!important;background-position:center!important;color:transparent!important}.pokerino-story-avatar{position:relative;width:168px;height:168px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#f2a66d,#8f472f);border:5px solid #321811;color:#17110b;font-size:68px;box-shadow:0 14px 30px rgba(0,0,0,.35),0 0 0 3px #ffc83d}.pokerino-story-scene>span{position:absolute;bottom:15px;color:#ffc83d;font-weight:600;letter-spacing:.16em}.pokerino-story-copy{padding:22px 18px calc(22px + env(safe-area-inset-bottom))}.pokerino-story-eyebrow{color:#ffc83d;font-size:11px;letter-spacing:.12em;font-weight:600}.pokerino-story-copy h2{margin:6px 0 8px;font-size:28px;line-height:1.05}.pokerino-story-copy>p{margin:0;color:#d7d3ca;font-size:14px;line-height:1.5}.pokerino-story-beats{display:grid;gap:8px;margin:18px 0}.pokerino-story-beats button{display:grid;grid-template-columns:30px 1fr;gap:10px;align-items:center;text-align:left;padding:11px;border:1px solid rgba(255,200,61,.25);border-radius:13px;background:#092219;color:#eee}.pokerino-story-beats b{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#ffc83d;color:#17110b}.pokerino-story-beats button.active{border-color:#ffc83d;background:#123529}.pokerino-story-actions{display:grid;grid-template-columns:1fr 1.25fr;gap:9px}.pokerino-story-actions button{min-height:48px;border-radius:14px;font-weight:600}.pokerino-audio{border:1px solid rgba(255,200,61,.45);background:#092219;color:#ffc83d}.pokerino-go{border:1px solid #ffd45b;background:linear-gradient(135deg,#ffd455,#f2a522);color:#171006}
    .pokerino-worlds{display:grid;gap:8px;margin:18px 0}.pokerino-worlds-title{color:#ffc83d;font-size:11px;letter-spacing:.1em;font-weight:600}.pokerino-worlds button{display:grid;grid-template-columns:38px 1fr 24px;align-items:center;gap:10px;text-align:left;padding:10px;border:1px solid rgba(255,200,61,.28);border-radius:14px;background:#081d16;color:#fff}.pokerino-worlds button>b{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:#173e30;color:#ffc83d;font-size:20px}.pokerino-worlds button span strong,.pokerino-worlds button span small{display:block}.pokerino-worlds button span strong{font-size:12px}.pokerino-worlds button span small{margin-top:3px;color:#aaa69d;font-size:11px;line-height:1.25}.pokerino-worlds button>i{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:rgba(255,200,61,.12);color:#ffc83d;font-style:normal;font-size:10px}.pokerino-worlds button.active{border-color:#ffc83d;background:#123529}
  `;document.head.appendChild(style);
  document.addEventListener('click',e=>{
    const stage=e.target.closest('[data-home-stage]');if(stage&&!e.target.closest('[data-pokerino-story]')){e.preventDefault();e.stopImmediatePropagation();open(stage.dataset.homeStage);return}
    const beat=e.target.closest('[data-story-beat]');if(beat){beat.classList.toggle('active');return}
    const world=e.target.closest('[data-poker-world]');if(world){world.parentElement.querySelectorAll('[data-poker-world]').forEach(x=>x.classList.remove('active'));world.classList.add('active');world.closest('[data-pokerino-story]').dataset.pokerWorld=world.dataset.pokerWorld;return}
    if(e.target.closest('[data-story-audio]')){const el=e.target.closest('[data-pokerino-story]'),story=stories[el?.dataset.pokerinoStory]||stories.fundamentos;speak(story.title+'. '+story.text+' '+story.beats.join(' '));return}
    if(e.target.closest('[data-story-close]')){stop();e.target.closest('[data-pokerino-story]')?.remove();return}
    if(e.target.closest('[data-story-go]')){const el=e.target.closest('[data-pokerino-story]'),key=el?.dataset.pokerinoStory||'fundamentos';stop();el?.remove();window.stage?.(key,1);return}
  },true);
  window.PokerinoStory={open,stop};
})();