(() => {
  const copy={
    'pt-BR':{
      home:'HOME',base:'BASE',modalities:'MODALIDADES',practice:'PRÁTICA',profile:'PERFIL',
      learn3:'APRENDA A JOGAR POKER EM 3 ETAPAS',buildBase:'CONSTRUA SUA BASE.',
      heroSub:'Aprenda. Pratique. Evolua.',continue:'CONTINUAR APRENDENDO',start:'COMEÇAR',
      continueLearning:'CONTINUAR APRENDENDO',threeSteps:'3 ETAPAS PRINCIPAIS',myEvolution:'MINHA EVOLUÇÃO',
      overallProgress:'PROGRESSO GERAL',answered:'QUESTÕES RESPONDIDAS',correct:'ACERTOS',errors:'ERROS',
      streak:'SEQUÊNCIA',weeklyGoal:'META SEMANAL',performance:'DESEMPENHO POR SEÇÃO',
      shortcuts:'ATALHOS',plans:'PLANOS',otherApps:'OUTROS APPS',language:'IDIOMA',
      free:'FREE',monthly:'MENSAL',semiannual:'SEMESTRAL',annual:'ANUAL',coachPlus:'COACH PLUS',
      currentPlan:'PLANO ATUAL',prepared:'DISPONÍVEL EM BREVE',subscribe:'ASSINAR',comingSoon:'EM BREVE',aboutPrivacy:'SOBRE E PRIVACIDADE',privacyPolicy:'POLÍTICA DE PRIVACIDADE',deleteLocalData:'APAGAR DADOS DESTE APARELHO',requestAccountDeletion:'SOLICITAR EXCLUSÃO DA CONTA',deleteLocalConfirm:'Apagar progresso, histórico, preferências e sessão local deste Academy?',localDataDeleted:'Dados locais do Academy apagados deste aparelho.',accountDeletionSubject:'Excluir minha conta - Academy',accountDeletionBody:'Solicito a exclusão da minha conta e dos dados sincronizados do StackUp Hold\'em Academy.',includedCoach:'2 MENSAGENS COACH/SEMANA INCLUÍDAS',ecosystem:'ECOSSISTEMA STACKUP',
      grinderCopy:'Pronto para transformar conhecimento em treino?',knowGrinder:'CONHEÇA O GRINDER',
      trainingLab:'LABORATÓRIO DE TREINO',back:'VOLTAR',next:'PRÓXIMO',review:'REVISAR',confirm:'CONFIRMAR',
      questions:'QUESTÕES',accuracy:'APROVEITAMENTO',lastSection:'ÚLTIMA SEÇÃO',nextStep:'PRÓXIMA ETAPA',focusDecision:'FOCO · DECISÃO · REPETIÇÃO',hands:'MÃOS',gameStructure:'ESTRUTURA DO JOGO',terminologyProfiles:'TERMINOLOGIA E PERFIS',formats:'FORMATOS',rulesConduct:'REGRAS E CONDUTA',profileCopy:'Preferências, plano do Academy e acesso ao ecossistema.',mainNav:'Navegação principal',personalRanking:'RANKING PESSOAL',history:'HISTÓRICO',exercises:'EXERCÍCIOS',practiceTools:'FERRAMENTAS DE PRÁTICA',selfRankingCopy:'Seu desempenho pessoal com base nos treinos já realizados.',historyCopy:'Treinos salvos por seção e sessão.',sessions:'SESSÕES',answeredShort:'RESPONDIDAS',historyEmpty:'Nenhum treino salvo no histórico ainda.',clearHistory:'APAGAR HISTÓRICO',clearHistoryConfirm:'Apagar somente o histórico de sessões? Seu progresso continuará salvo.',evolutionCategory:'CATEGORIA',toNextCategory:'PARA A PRÓXIMA CATEGORIA',maxCategory:'CATEGORIA MÁXIMA',exercisesCopy:'Acesse rapidamente os exercícios existentes sem criar conteúdo paralelo.',simulator:'SIMULADOR',quiz:'QUIZ',mathPoker:'MATEMÁTICA DO POKER',simulatorCopy:'Treine decisões e regras das modalidades existentes.',quizCopy:'Revise conceitos e retenção.',mathPokerCopy:'Treine os cálculos já disponíveis.',advancedStudy:'ESTUDO AVANÇADO',advancedStudyCopy:'Use seus dados de treino para direcionar a próxima etapa.',smartReview:'REVISÃO INTELIGENTE',smartReviewCopy:'As competências com menor aproveitamento aparecem primeiro.',timedExam:'SIMULADO CRONOMETRADO',timedExamCopy:'20 questões sorteadas de todo o banco geral, com limite de 12 minutos.',certificates:'CERTIFICADOS',certificatesCopy:'A conquista é liberada por seção ao atingir os dois critérios.',skillReport:'RELATÓRIO POR COMPETÊNCIA',skillReportCopy:'Competências ordenadas da menor para a maior taxa de acerto.',open:'ABRIR',studyNow:'ESTUDAR AGORA',reviewEmpty:'Treine algumas questões para receber recomendações.',examPreparing:'Preparando 20 questões sorteadas do Academy...',loading:'CARREGANDO...',examNoFeedback:'Responda sem feedback imediato. O resultado aparece ao final.',examResult:'RESULTADO DO SIMULADO',examTimeout:'O tempo terminou. Veja o resultado das questões respondidas.',examFinished:'Simulado concluído.',newExam:'NOVO SIMULADO',lastExam:'ÚLTIMO SIMULADO',startExam:'INICIAR SIMULADO',progress:'PROGRESSO',certificateEarned:'CERTIFICADO CONQUISTADO',certificateRule:'Necessário 80% de progresso e 80% de acertos.',heroMe:'EU HERÓI',villainMe:'EU VILÃO'
    },
    'en-US':{
      home:'HOME',base:'BASE',modalities:'GAME TYPES',practice:'PRACTICE',profile:'PROFILE',
      learn3:'LEARN TO PLAY POKER IN 3 STEPS',buildBase:'BUILD YOUR FOUNDATION.',
      heroSub:'Learn. Practice. Evolve.',continue:'CONTINUE LEARNING',start:'START',
      continueLearning:'CONTINUE LEARNING',threeSteps:'3 CORE STEPS',myEvolution:'MY EVOLUTION',
      overallProgress:'OVERALL PROGRESS',answered:'QUESTIONS ANSWERED',correct:'CORRECT',errors:'ERRORS',
      streak:'STREAK',weeklyGoal:'WEEKLY GOAL',performance:'PERFORMANCE BY SECTION',
      shortcuts:'SHORTCUTS',plans:'PLANS',otherApps:'OTHER APPS',language:'LANGUAGE',
      free:'FREE',monthly:'MONTHLY',semiannual:'SEMIANNUAL',annual:'ANNUAL',coachPlus:'COACH PLUS',
      currentPlan:'CURRENT PLAN',prepared:'COMING SOON',subscribe:'SUBSCRIBE',comingSoon:'COMING SOON',aboutPrivacy:'ABOUT AND PRIVACY',privacyPolicy:'PRIVACY POLICY',deleteLocalData:'DELETE DATA FROM THIS DEVICE',requestAccountDeletion:'REQUEST ACCOUNT DELETION',deleteLocalConfirm:'Delete Academy progress, history, preferences and local session from this device?',localDataDeleted:'Local Academy data deleted from this device.',accountDeletionSubject:'Delete my Academy account',accountDeletionBody:'I request deletion of my StackUp Hold\'em Academy account and synchronized data.',includedCoach:'2 COACH MESSAGES/WEEK INCLUDED',ecosystem:'STACKUP ECOSYSTEM',
      grinderCopy:'Ready to turn knowledge into training?',knowGrinder:'DISCOVER GRINDER',
      trainingLab:'TRAINING LAB',back:'BACK',next:'NEXT',review:'REVIEW',confirm:'CONFIRM',
      questions:'QUESTIONS',accuracy:'ACCURACY',lastSection:'LAST SECTION',nextStep:'NEXT STEP',focusDecision:'FOCUS · DECISION · REPETITION',hands:'HANDS',gameStructure:'GAME STRUCTURE',terminologyProfiles:'TERMINOLOGY & PROFILES',formats:'FORMATS',rulesConduct:'RULES & CONDUCT',profileCopy:'Preferences, Academy plan and ecosystem access.',mainNav:'Main navigation',personalRanking:'PERSONAL RANKING',history:'HISTORY',exercises:'EXERCISES',practiceTools:'PRACTICE TOOLS',selfRankingCopy:'Your personal performance based on completed training.',historyCopy:'Training saved by section and session.',sessions:'SESSIONS',answeredShort:'ANSWERED',historyEmpty:'No training sessions saved yet.',clearHistory:'CLEAR HISTORY',clearHistoryConfirm:'Clear session history only? Your progress will remain saved.',evolutionCategory:'CATEGORY',toNextCategory:'TO NEXT CATEGORY',maxCategory:'MAX CATEGORY',exercisesCopy:'Quick access to existing exercises without duplicating content.',simulator:'SIMULATOR',quiz:'QUIZ',mathPoker:'MATH OF POKER',simulatorCopy:'Train decisions and rules from the existing game types.',quizCopy:'Review concepts and retention.',mathPokerCopy:'Practice the calculations already available.',advancedStudy:'ADVANCED STUDY',advancedStudyCopy:'Use your training data to direct the next step.',smartReview:'SMART REVIEW',smartReviewCopy:'Skills with lower accuracy appear first.',timedExam:'TIMED EXAM',timedExamCopy:'20 random questions from the general bank with a 12-minute limit.',certificates:'CERTIFICATES',certificatesCopy:'Earned by section after meeting both criteria.',skillReport:'SKILL REPORT',skillReportCopy:'Skills ordered from lowest to highest accuracy.',open:'OPEN',studyNow:'STUDY NOW',reviewEmpty:'Train a few questions to receive recommendations.',examPreparing:'Preparing 20 random Academy questions...',loading:'LOADING...',examNoFeedback:'Answer without immediate feedback. Results appear at the end.',examResult:'EXAM RESULT',examTimeout:'Time is up. Review the result for the questions answered.',examFinished:'Exam completed.',newExam:'NEW EXAM',lastExam:'LAST EXAM',startExam:'START EXAM',progress:'PROGRESS',certificateEarned:'CERTIFICATE EARNED',certificateRule:'Requires 80% progress and 80% accuracy.',heroMe:'HERO ME',villainMe:'VILLAIN ME'
    }
  };
  const lang=()=>{try{return localStorage.getItem('stackup-language-v1')==='en-US'?'en-US':'pt-BR'}catch(_){return 'pt-BR'}};
  const t=(key,fallback='')=>copy[lang()]?.[key]??copy['pt-BR'][key]??fallback??key;
  const applyStaticCopy=()=>{const sub=document.querySelector('.brand .sub');if(sub)sub.textContent=t('learn3','APRENDA A JOGAR POKER EM 3 ETAPAS');document.documentElement.lang=lang();};
  window.AcademyI18n={copy,lang,t,applyStaticCopy};applyStaticCopy();
})();